PAP-29: Модели, Контроллер, Конфигурация БД для Psychologist. Общие м…
joshkhdev/psy-assist-platform pull request #32
Opened 2024-04-01 22:19 UTC by miitrei

…оменты по маппингу и тестовым данным

2024-04-02 06:40 UTC, artcolumbo requested changes

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.Persistence/DbInitializer.cs
> +    #region Fake Data Tests
Regions засоряют код, использовать их рекомендуют в крайних случаях.

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.Persistence/DbInitializer.cs
> +    }
Зачем в тестовые данные добавлять асинхронно? 
Все можно сделать куда красивее, например:
public void Initialize()
    {
        _context.Database.EnsureDeleted();
        _context.Database.EnsureCreated();
        
        _context.AddRange(FakeDataFactory...);
        _context.AddRange(FakeDataFactory...);
        _context.AddRange(FakeDataFactory...);
        _context.AddRange(FakeDataFactory....);
        _context.AddRange(FakeDataFactory....);
        
        _context.SaveChanges();
    }

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.Persistence/DbInitializer.cs
> +        return;
Зачем здесь return ?

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.Persistence/EntityTypeConfigurations/PsychologistConfiguration.cs
> +        builder.Property(psychologist => psychologist.TimeZone).HasMaxLength(250).IsRequired();
Зачем для TimeZone 250 знаков?

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.Persistence/FakeDataFactory.cs
> +                    Role = Roles.First(),
Когда заполняешь фейковые данные, не нужно заполнять объект, нужно заполнять только Id, тогда проблемы отслеживания не будет!

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.Persistence/FakeDataFactory.cs
> +                User = Users.First(),
Не нужно инициализировать User, используй только UserId.

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/PsychologistController.cs
> +    public class PsychologistController(
Контроллеры обычно именование сущности во множественном числе, например PsychologistsController. Так формируется строка запроса правильно, с точки зрения англ. языка.

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/PsychologistController.cs
> +        public async Task<IActionResult> UpdateAsync(int id, UpdatePsychologistRequest request)
В методе Update передается сущность.

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/PsychologistController.cs
> +        IMapper mapper) : ControllerBase
Данные, которые передаются в контроллер, нужно сохранять в локальных readonly переменных, или уже передавать их так, передаются в record, в формате UpperCase. Предлагаю использовать все-таки вариант с readonly переменными.

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/PsychologistController.cs
> +        public async Task<IActionResult> UpdateAsync(int id, UpdatePsychologistRequest request)
Во всех методах неправильно передается Cancellation token! Какой смысл в таком коде? Cancellation token передается последним аргументом в методе, например:  
public async Task<IActionResult> UpdateAsync(UpdatePsychologistRequest request, CancellationToken cancellationToken)

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Models/Psychologist/CreatePsychologistRequest.cs
> +    public class CreatePsychologistRequest
Для DTO договорились использовать record, а не class.

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Models/Psychologist/PsychologistResponse.cs
> +    //public UserResponse User { get; set; }
Закомментированные строчки нужно убирать из PR.

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Models/Psychologist/PsychologistShortResponse.cs
> +
Record, а не class

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Models/Psychologist/UpdatePsychologistRequest.cs
> +    {
Record

2024-04-02 06:40 UTC, artcolumbo commented on PsyAssistPlatform.Persistence/FakeDataFactory.cs
> +    public static class FakeDataFactory
Предлагаю поместить этот класс в папку "Data", т.е. PsyAssistPlatform.Persistence.Data

2024-04-02 07:05 UTC, artcolumbo requested changes

2024-04-02 07:05 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/PsychologistController.cs
> +namespace PsyAssistPlatform.WebApi.Controllers
Договорились не использовать "открытый" namespace.

2024-04-02 10:54 UTC, miitrei commented on PsyAssistPlatform.WebApi/Controllers/PsychologistController.cs
> +        IMapper mapper) : ControllerBase
Это просто primary consctructor, для простоты (Rider, по идее, тоже должен предлагать заменить). Мне не принципиально, как это делать, вернул под readonly переменные, если в целом привычнее. Я так сделал, потому что мы в начале договаривались по оформлению кода следовать рекомендациям Решарпера

2024-04-02 12:06 UTC, artcolumbo requested changes

2024-04-02 12:06 UTC, artcolumbo commented on PsyAssistPlatform.Persistence/DbInitializer.cs
>  {
Почему мы объявляем булевскую переменную как const? Я бы рекомендовал вообще отказаться от лишнего флага, пока идет разработка, мы заполняем БД тестовыми данными, не нужна еще внутренняя логика.

2024-04-02 12:06 UTC, artcolumbo commented on PsyAssistPlatform.Persistence/DbInitializer.cs
> +            await Task.WhenAll(tasks);
Зачем этот метод? Работу методов можно посмотреть в Swagger.

2024-04-02 12:06 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/PsychologistsController.cs
> +        IMapper mapper)
Если переносим аргументы, то нужно переносить все для удобочитаемости кода:
public PsychologistsController(
        IRepository<Psychologist> psychologistRepository,
        IRepository<User> userRepository,
        IMapper mapper)

2024-04-02 12:06 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/PsychologistsController.cs
> +        int id,
Зачем здесь идентификатор? Я уже писал об этом в замечании в первом PR.

2024-04-02 17:57 UTC, miitrei commented on PsyAssistPlatform.Persistence/Data/FakeDataFactory.cs
> +namespace PsyAssistPlatform.Persistence.Data
Пропустил, поправлю

2024-04-02 18:00 UTC, miitrei commented on PsyAssistPlatform.Persistence/DbInitializer.cs
> +            await Task.WhenAll(tasks);
Метод написал, чтобы до реализации контроллеров посмотреть, какие данные мы получили из БД и сравнить. Например, в случае, если сваггер выдает ошибку. Чисто для теста и отслеживания ошибок на промежуточных этапах. Считаю его полезным на время разработки контроллеров.
Этот пункт оставлю пока на ревью, чтобы еще кто-то отписался.

2024-04-02 18:00 UTC, miitrei commented on PsyAssistPlatform.WebApi/Controllers/PsychologistsController.cs
> +        IMapper mapper)
Спасибо, пропустил, поправлю

2024-04-08 17:12 UTC, joshkhdev approved these changes

2024-04-08 17:30 UTC, artcolumbo approved these changes

2024-04-12 09:56 UTC, A1exShap approved these changes

2024-04-12 10:23 UTC, merged