Pap 31
joshkhdev/psy-assist-platform pull request #33
Opened 2024-04-12 18:50 UTC by andrea20024

2024-04-14 13:53 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/RolesController.cs
> +                return BadRequest("No data to fill out");
Может стоит поменять сообщение, например на "Empty request"/"Request is empty".

2024-04-14 18:39 UTC, andrea20024 commented on PsyAssistPlatform.WebApi/Controllers/RolesController.cs
> +                return BadRequest("No data to fill out");
> Может стоит поменять сообщение, например на "Empty request"/"Request is empty".

Да, можно.
Думаю, надо обсудить вынос часть текстов в общую часть. Проверка на null запроса должна быть в каждом методе создания и обновления объекта. Чтобы не дублировать по много раз.

2024-04-15 15:11 UTC, A1exShap commented
Namespaces указываем без фигурных скобок

2024-04-15 16:17 UTC, joshkhdev requested changes

2024-04-15 16:17 UTC, joshkhdev commented on PsyAssistPlatform.Persistence/Data/FakeDataFactory.cs
> +                    Name = "Psychoanalysis"
Лучше единообразно или в lower case или в Pascal Case

2024-04-15 16:17 UTC, joshkhdev commented on PsyAssistPlatform.WebApi/Models/Approach/ApproachShortResponse.cs
Получается ShortResponse не отличается от простого Response, тогда он и не нужен

2024-04-15 16:17 UTC, joshkhdev commented on PsyAssistPlatform.WebApi/Controllers/StatusesController.cs
> +                return NotFound($"Status {id} doesn't found");
"doesn't found" - не согласовано по времени
"wasn't found" или просто "not found"

2024-04-15 18:00 UTC, andrea20024 commented
Залил изменения

2024-04-17 05:59 UTC, A1exShap approved these changes

2024-04-18 12:37 UTC, joshkhdev approved these changes

2024-04-19 21:42 UTC, miitrei approved these changes

2024-04-22 17:42 UTC, merged