Add contact
joshkhdev/psy-assist-platform pull request #34
Opened 2024-04-15 15:04 UTC by A1exShap

2024-04-15 16:19 UTC, joshkhdev commented on PsyAssistPlatform.Persistence/Data/FakeDataFactory.cs
> +                Email = "ivanov@gmail.com",
Похоже на существующую почту, лучше выдумать какой-нибудь почтовый домен "@somemail.ru" или рандомный генератор попросить

2024-04-15 16:20 UTC, joshkhdev commented on PsyAssistPlatform.WebApi/Controllers/ContactsController.cs
> +        => Ok(_mapper.Map<IEnumerable<ContactResponse>>(
Не удобно читать и редактировать сокращенную запись, лучше развернуть в стандартный формат {}

2024-04-15 16:24 UTC, joshkhdev requested changes

2024-04-15 16:24 UTC, joshkhdev commented on PsyAssistPlatform.WebApi/Controllers/ContactsController.cs
> +        return Ok(new { id = contact.Id });
А зачем такой странный объект возвращаем? Может лучше полную сущность или просто Ok()?

2024-04-15 16:24 UTC, joshkhdev commented on PsyAssistPlatform.WebApi/Controllers/ContactsController.cs
> +        return Ok(new { id = contact.Id });
Просто отдать все поля которые есть, если какого-то нет - тогда null

2024-04-17 06:15 UTC, artcolumbo approved these changes

2024-04-19 21:40 UTC, miitrei approved these changes

2024-04-19 21:41 UTC, merged