Pap 27 Add Questionnaire
joshkhdev/psy-assist-platform pull request #35
Opened 2024-04-17 14:28 UTC by AlexChalenko

2024-04-18 12:39 UTC, joshkhdev commented on PsyAssistPlatform.Persistence/Data/FakeDataFactory.cs
> +                    Name = "hyponosis"
Делаем единообразно, с заглавной "Hyponosis"

2024-04-18 12:43 UTC, joshkhdev commented on PsyAssistPlatform.Persistence/EntityTypeConfigurations/ContactConfiguration.cs
> +        builder.Property(contact => contact.Email).HasMaxLength(50);
На почту нужно больше знаков, предлагаю 250
На телеграм меньше, официально от 5 до 32, но предлагаю оставить только верхнюю планку в 50

2024-04-18 12:46 UTC, joshkhdev commented on PsyAssistPlatform.Persistence/EntityTypeConfigurations/QuestionnaireConfiguration.cs
> +        builder.HasOne(questionnaire => questionnaire.Contact)
Есть укороченная запись "OwnsOne"

2024-04-18 12:58 UTC, joshkhdev requested changes

2024-04-18 12:58 UTC, joshkhdev commented on PsyAssistPlatform.WebApi/Controllers/ApproachesController.cs
> +                return NotFound($"Approach {id} doesn't found");
Лучше единообразно "... not found"

2024-04-18 12:58 UTC, joshkhdev commented on PsyAssistPlatform.WebApi/Controllers/QuestionnaireController.cs
> +        public async Task<IEnumerable<QuestionnaireShortResponse>> GetAllQuestionnaireAsync(CancellationToken cancellationToken)
Кажется должно быть во множественном числе "GetAllQuestionnairesAsync"

2024-04-18 12:58 UTC, joshkhdev commented on PsyAssistPlatform.WebApi/Controllers/QuestionnaireController.cs
> +            await _contactRepository.DeleteAsync(questionnaire.Contact.Id, cancellationToken);
Если каскадное удаление настроено - это не потребуется

2024-04-18 13:19 UTC, artcolumbo requested changes

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/ApproachesController.cs
> +{
Namespace делаем без { }

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.Persistence/Data/FakeDataFactory.cs
> +                    Name = "Admin"
Мы пока не обсуждали, но для боевых данных я бы предложил, что Admin с Id = 1, Curator c Id = 2, и т.д. -> от более главной роли к менее.

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/ApproachesController.cs
> +        private readonly IMapper _mapper;
Принято добавлять пустую строку перед конструктором (можно исправить уже потом во всех классах, где есть такой момент).

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/QuestionnaireController.cs
> +namespace PsyAssistPlatform.WebApi.Controllers
Namespace пишем без { }.

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/RolesController.cs
> +{
Namespace пишем без { }

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/StatusesController.cs
> +{
Namespace пишем без { }

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Models/Approach/ApproachResponse.cs
> +﻿namespace PsyAssistPlatform.WebApi.Models.Approach
Namespace пишем без { }

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Models/Approach/ApproachShortResponse.cs
> +{
Namespace пишем без { }

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Models/Approach/CreateApproachRequest.cs
> +{
Namespace пишем без { }

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Models/Approach/UpdateApproachRequest.cs
> +{
Namespace пишем без { }

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Models/Role/RoleShortResponse.cs
> +{
Namespace пишем без { }

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Models/Role/UpdateRoleRequest.cs
> +{
Namespace пишем без { }

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Models/Status/CreateStatusRequest.cs
> +{
Namespace пишем без { }

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Models/Status/StatusShortResponse.cs
> +{
Namespace пишем без { }

2024-04-18 13:19 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Models/Status/UpdateStatusRequest.cs
> +{
Namespace пишем без { }

2024-04-21 07:11 UTC, AlexChalenko commented on PsyAssistPlatform.Persistence/Data/FakeDataFactory.cs
> +                    Name = "hyponosis"
готово

2024-04-21 07:11 UTC, AlexChalenko commented on PsyAssistPlatform.Persistence/EntityTypeConfigurations/ContactConfiguration.cs
> +        builder.Property(contact => contact.Email).HasMaxLength(50);
готово

2024-04-21 07:12 UTC, AlexChalenko commented on PsyAssistPlatform.Persistence/EntityTypeConfigurations/QuestionnaireConfiguration.cs
> +        builder.Property(questionnaire => questionnaire.Name).HasMaxLength(50).IsRequired();
готово

2024-04-21 07:15 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Controllers/ApproachesController.cs
> +        private readonly IMapper _mapper;
готово

2024-04-21 07:15 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Controllers/ApproachesController.cs
> +{
готово

2024-04-21 07:16 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Controllers/ApproachesController.cs
> +                return NotFound($"Approach {id} doesn't found");
готово

2024-04-21 07:16 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Controllers/QuestionnaireController.cs
> +namespace PsyAssistPlatform.WebApi.Controllers
готово

2024-04-21 07:17 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Controllers/QuestionnaireController.cs
> +            await _contactRepository.DeleteAsync(questionnaire.Contact.Id, cancellationToken);
готово

2024-04-21 07:18 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Controllers/QuestionnaireController.cs
> +        public async Task<IEnumerable<QuestionnaireShortResponse>> GetAllQuestionnaireAsync(CancellationToken cancellationToken)
готово

2024-04-21 07:18 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Controllers/RolesController.cs
> +{
готово

2024-04-21 07:18 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Controllers/StatusesController.cs
> +{
готово

2024-04-21 07:19 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Models/Approach/ApproachResponse.cs
> +﻿namespace PsyAssistPlatform.WebApi.Models.Approach
готово

2024-04-21 07:19 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Models/Approach/ApproachShortResponse.cs
> +{
готово

2024-04-21 07:19 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Models/Approach/CreateApproachRequest.cs
> +{
готово

2024-04-21 07:19 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Models/Approach/UpdateApproachRequest.cs
> +{
готово

2024-04-21 07:21 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Models/Questionnaire/QuestionnaireShortResponse.cs
> +    public DateTime RegistrationDate { get; set; }
нет никакого смысла добавлять пустую строку. Это вопрос личных предпочтений

2024-04-21 07:21 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Models/Role/RoleShortResponse.cs
> +{
готово

2024-04-21 07:22 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Models/Role/UpdateRoleRequest.cs
> +{
готово

2024-04-21 07:22 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Models/Status/CreateStatusRequest.cs
> +{
готово

2024-04-21 07:22 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Models/Status/StatusShortResponse.cs
> +{
готово

2024-04-21 07:22 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Models/Status/UpdateStatusRequest.cs
> +{
готово

2024-04-21 07:25 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Models/Questionnaire/QuestionnaireResponse.cs
> +    public string TherapyExperience { get; set; }
нет никакого смысла добавлять пустую строку. Это вопрос личных предпочтений

2024-04-21 07:27 UTC, AlexChalenko commented on PsyAssistPlatform.Persistence/EntityTypeConfigurations/QuestionnaireConfiguration.cs
> +        builder.HasOne(questionnaire => questionnaire.Contact)
насколько я понял из документации OwnsOne служи для моделирования вдаления, а не для моделирования связи один-к-одному

2024-04-22 18:16 UTC, merged

2024-04-22 18:20 UTC, joshkhdev commented on PsyAssistPlatform.Persistence/EntityTypeConfigurations/QuestionnaireConfiguration.cs
> +        builder.HasOne(questionnaire => questionnaire.Contact)
У нас вроде как раз такой случай, контакта без анкеты не будет
Но в целом не обязательно
+