PAP-30: User controller + User DTOs + User entity configuration
joshkhdev/psy-assist-platform pull request #36
Opened 2024-04-20 14:46 UTC by joshkhdev

2024-04-20 17:18 UTC, artcolumbo requested changes

2024-04-20 17:30 UTC, joshkhdev commented on PsyAssistPlatform.Persistence/EntityTypeConfigurations/UserConfiguration.cs
> -        // TODO: реализовать
Красная строка и минус - удалено, в коде этого коммента больше нет

2024-04-20 17:54 UTC, artcolumbo approved these changes

2024-04-20 18:00 UTC, joshkhdev commented on PsyAssistPlatform.WebApi/Controllers/UsersController.cs
> +        }
+

2024-04-20 18:00 UTC, joshkhdev commented on PsyAssistPlatform.WebApi/Controllers/UsersController.cs
> +        }
Поправил

2024-04-20 18:00 UTC, joshkhdev commented on PsyAssistPlatform.WebApi/Controllers/UsersController.cs
> +        }
Поправил

2024-04-22 11:06 UTC, miitrei approved these changes

2024-04-22 17:05 UTC, merged