[PAP-37] [RF][CF] Добавлен слой бизнес-логики, произведен рефакторинг
joshkhdev/psy-assist-platform pull request #43
Opened 2024-05-14 14:22 UTC by artcolumbo

2024-05-22 05:59 UTC, joshkhdev requested changes

2024-05-22 05:59 UTC, joshkhdev commented on PsyAssistPlatform.Application/Services/PsychologistProfileService.cs
> +        IRepository<User> useRepository,
Опечатка userRepository

2024-05-22 05:59 UTC, joshkhdev commented on PsyAssistPlatform.WebApi/Controllers/PsychologistProfilesController.cs
> +    [HttpPut("{id:int}/{isActive:bool}")]
Думаю вместо такого очень специфичного эндпоинта сделать обычный patch с возможностью поменять одно или несколько полей у профиля

2024-05-22 07:07 UTC, A1exShap approved these changes

2024-05-22 07:41 UTC, artcolumbo commented on PsyAssistPlatform.Application/Services/ContactService.cs
> +        if (string.IsNullOrEmpty(contactData.Email)
Done

2024-05-22 07:41 UTC, artcolumbo commented on PsyAssistPlatform.Application/Services/PsychologistProfileService.cs
> +        IRepository<User> useRepository,
Done

2024-05-22 07:42 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/PsychologistProfilesController.cs
> +    [HttpPut("{id:int}/{isActive:bool}")]
Изменил endpoint

2024-05-22 08:38 UTC, joshkhdev approved these changes

2024-05-23 17:16 UTC, miitrei approved these changes

2024-05-24 11:44 UTC, merged