[PAP-49] [NF][CF] Unit-тесты, переход на PostgreSQL
joshkhdev/psy-assist-platform pull request #55
Opened 2024-06-15 20:43 UTC by artcolumbo

2024-06-17 14:21 UTC, joshkhdev requested changes

2024-06-17 14:21 UTC, joshkhdev commented on PsyAssistPlatform.Tests/Application/Services/ContactServiceTests.cs
> +    [InlineData("+7(999)123-45-67")]
Мне кажется не надо делать exception если номер с немного необычном форматом
Скобочки и черточки можем просто на входе убирать через string.Replace, а + добавлять при необходимости
А валидация на мой взгляд должна проверять длину и наличие цифр, а не их формат

2024-06-17 14:28 UTC, artcolumbo commented on PsyAssistPlatform.Tests/Application/Services/ContactServiceTests.cs
> +    [InlineData("+7(999)123-45-67")]
Мы же обсуждали, что с фронта данные будут приходить в определенном формате, поэтому в БД не будет разных вариаций номера телефона.
Валидация сейчас проверяет длину и формат (цифры и +), это сделано было еще раньше, ты одобрил. Когда номера в БД будут в одном формате, будет намного проще делать поиск, если будем делать проверку на первое обращение клиента.

2024-06-17 14:48 UTC, artcolumbo commented on PsyAssistPlatform.Tests/Application/Services/ContactServiceTests.cs
> +    [InlineData("+7(999)123-45-67")]
Где делать? На бэке?

2024-06-17 17:07 UTC, joshkhdev approved these changes

2024-06-17 17:07 UTC, joshkhdev commented on PsyAssistPlatform.Tests/Application/Services/ContactServiceTests.cs
> +    [InlineData("+7(999)123-45-67")]
Решили это делать на клиенте

2024-06-18 20:44 UTC, A1exShap approved these changes

2024-06-19 10:11 UTC, merged