66 dev logging
joshkhdev/psy-assist-platform pull request #69
Opened 2024-07-23 09:28 UTC by A1exShap

2024-07-23 12:04 UTC, joshkhdev approved these changes

2024-07-29 07:44 UTC, artcolumbo requested changes
Не используем в коде namespace со скобками.

2024-07-29 07:48 UTC, artcolumbo requested changes

2024-07-29 07:48 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Middlewares/LoggingHandlerMiddleware.cs
> +    private async Task<string> ReadRequestBody(HttpContext context)
Асинхронные методы принято именовать с суффиксом Async

2024-07-29 07:48 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Services/CurrentUserService.cs
> +namespace PsyAssistPlatform.WebApi.Services
Не используем namespace со скобками.

2024-07-29 08:32 UTC, miitrei commented on PsyAssistPlatform.WebApi/Contracts/ICurrentUserService.cs
> +{
Лишние скобки в namespace

2024-07-29 11:16 UTC, A1exShap commented on PsyAssistPlatform.WebApi/Middlewares/LoggingHandlerMiddleware.cs
> +    private async Task<string> ReadRequestBody(HttpContext context)
Исправлено

2024-07-29 11:16 UTC, A1exShap commented on PsyAssistPlatform.WebApi/Services/CurrentUserService.cs
> +namespace PsyAssistPlatform.WebApi.Services
Исправлено

2024-07-29 11:16 UTC, A1exShap commented on PsyAssistPlatform.WebApi/Contracts/ICurrentUserService.cs
> +{
Исправлено

2024-07-29 11:20 UTC, artcolumbo approved these changes

2024-07-30 05:20 UTC, merged