[PAP-44] Поддержка аутентификации и авторизации
joshkhdev/psy-assist-platform pull request #77
Opened 2024-08-17 14:03 UTC by AlexChalenko

2024-08-18 16:51 UTC, joshkhdev approved these changes

2024-08-20 08:27 UTC, artcolumbo requested changes

2024-08-20 08:27 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Extensions/SwaggerServiceExtensions.cs
> +namespace PsyAssistPlatform.WebApi.Extensions
Не используем namespace со скобками

2024-08-20 08:27 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Startup.cs
> +                options.Authority = Configuration["Jwt:Authority"];
Не поплыла табуляция?

2024-08-20 08:27 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/TokenValidation/CustomTokenRequestValidator.cs
> +{
Не используем namespace с фигурными скобками

2024-08-20 08:27 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/TokenValidation/CustomTokenRequestValidator.cs
> +                if (!string.IsNullOrEmpty(roleClaim))
Лучше использовать IsNullOrWhiteSpace

2024-08-20 19:33 UTC, miitrei approved these changes

2024-08-22 20:49 UTC, A1exShap approved these changes

2024-08-23 07:53 UTC, AlexChalenko commented on PsyAssistPlatform.WebApi/Extensions/SwaggerServiceExtensions.cs
> +namespace PsyAssistPlatform.WebApi.Extensions
готово

2024-08-23 07:57 UTC, artcolumbo approved these changes

2024-08-23 08:10 UTC, merged