Получение контента психолога
joshkhdev/psy-assist-platform pull request #80
Opened 2024-08-20 18:57 UTC by andrea20024

2024-08-20 19:25 UTC, miitrei commented on PsyAssistPlatform.Application/Integrations/Content/Content.cs
> +public class Content : IContent
Смущает название класса и интерфейса, это не модель, а сервис или что-то в этом духе
и возникает путаница с response.Content

2024-08-20 19:52 UTC, andrea20024 commented on PsyAssistPlatform.Application/Integrations/Content/Content.cs
> +public class Content : IContent
Поправил

2024-08-21 08:04 UTC, artcolumbo requested changes

2024-08-21 08:04 UTC, artcolumbo commented on PsyAssistPlatform.Application/Integrations/Content/FileMetadata.cs
> +﻿namespace PsyAssistPlatform.Application.Integrations.Content;
Предлагаю следующий namespace - PsyAssistPlatform.Application.Integrations.Dto, если это тип, отвечающий за передачу данных

2024-08-21 08:04 UTC, artcolumbo commented on PsyAssistPlatform.Application/Integrations/Content/FileMetadata.cs
> +}
Если это тип DTO, то нужно использовать record

2024-08-21 08:10 UTC, artcolumbo commented
У нас принято называть коммиты следующим образом - "Номер карточки" "Комментарий". Если правильно понимаю, то этот коммит относится к карточке [PAP-64]

2024-08-21 19:01 UTC, andrea20024 commented on PsyAssistPlatform.Application/Integrations/Content/FileMetadata.cs
> +}
Это не DTO. Это фильтр

2024-08-21 19:25 UTC, andrea20024 commented on PsyAssistPlatform.Application/Interfaces/Integration/IContent.cs
> +    Task<string> GetContent(int psyId, int type, CancellationToken cancellationToken);
Метод ReadAsStringAsync возвращает Task<string>
А если что-то пойдет не так, то метод EnsureSuccessStatusCode выбросит исключение

2024-08-21 19:26 UTC, andrea20024 commented on PsyAssistPlatform.WebApi/Controllers/PsychologistProfilesController.cs
>      private readonly IMapper _mapper;
ok

2024-08-21 19:26 UTC, andrea20024 commented on PsyAssistPlatform.Application/Integrations/Content/FileMetadata.cs
> +﻿namespace PsyAssistPlatform.Application.Integrations.Content;
Это не DTO. Это фильтр

2024-08-21 19:27 UTC, andrea20024 commented on PsyAssistPlatform.WebApi/Controllers/PsychologistProfilesController.cs
> +    [HttpPost("{id:int}/content")]
Предполагал/предполагаю тело запроса

2024-08-22 06:28 UTC, artcolumbo requested changes

2024-08-22 06:28 UTC, artcolumbo commented on PsyAssistPlatform.Application/Integrations/Content/Content.cs
> +    public async Task<string> GetContent(int psyId, int type, CancellationToken cancellationToken)
Асинхронные методы помечаем суффиксом async

2024-08-22 06:28 UTC, artcolumbo commented on PsyAssistPlatform.Application/Interfaces/Integration/IContent.cs
> +    Task<string> GetContent(int psyId, int type, CancellationToken cancellationToken);
Метод будет асинхронный - помечаем суффиксом async

2024-08-22 06:28 UTC, artcolumbo commented on PsyAssistPlatform.WebApi/Controllers/PsychologistProfilesController.cs
> +    [HttpPost("{id:int}/content")]
Это не является стандартной практикой, точнее - это bad practice и не соответствует подходу RESTful.
Использование метода POST вместо GET может ввести в заблуждение тех, кто будет работать с вашим API в будущем. 
Возможно стоит рассмотреть использование GET-параметров. 
Какие данные необходимо передавать в теле запроса?

2024-08-22 10:55 UTC, artcolumbo requested changes

2024-08-22 10:55 UTC, artcolumbo commented on PsyAssistPlatform.Application/Integrations/Content/Content.cs
> +public class ContentService : IContentService
Файл тоже нужно переименовать.
Файл - Content, class - ContentService

2024-08-22 15:05 UTC, A1exShap approved these changes

2024-08-23 19:03 UTC, andrea20024 commented on PsyAssistPlatform.WebApi/Controllers/PsychologistProfilesController.cs
> +    [HttpPost("{id:int}/content")]
Поставил Get

2024-08-23 19:04 UTC, andrea20024 commented on PsyAssistPlatform.Application/Integrations/Content/Content.cs
> +    public async Task<string> GetContent(int psyId, int type, CancellationToken cancellationToken)
Поправил

2024-08-23 19:04 UTC, andrea20024 commented on PsyAssistPlatform.Application/Interfaces/Integration/IContent.cs
> +    Task<string> GetContent(int psyId, int type, CancellationToken cancellationToken);
Поправил

2024-08-23 19:04 UTC, andrea20024 commented on PsyAssistPlatform.Application/Integrations/Content/Content.cs
> +public class ContentService : IContentService
Поправил

2024-08-24 08:13 UTC, artcolumbo commented
У тебя также различия в названиях файлов и типов в них. Файл - IContent, тип IContentService. Потом будет сложно искать, т.к. в ide мы не будем видеть нужный тип.

2024-08-24 08:24 UTC, artcolumbo requested changes

2024-08-24 08:24 UTC, artcolumbo commented on PsyAssistPlatform.Application/Interfaces/Integration/IContent.cs
> +public interface IContentService
У тебя также различия в названиях файлов и типов в них. Файл - IContent, тип IContentService. Потом будет сложно искать, т.к. в ide мы не будем видеть нужный тип.

2024-08-24 08:44 UTC, andrea20024 commented on PsyAssistPlatform.Application/Interfaces/Integration/IContent.cs
> +public interface IContentService
Поправил

2024-08-24 08:45 UTC, artcolumbo approved these changes

2024-08-24 08:49 UTC, merged