[PAP-85] [RF][CF] Изменение структуры проекта для разворачивания в docker, добавление docker-compose
joshkhdev/psy-assist-platform pull request #86
Opened 2024-08-25 15:52 UTC by artcolumbo

2024-08-25 20:17 UTC, joshkhdev commented
Залил правки конфига по предложению от Алексея

2024-08-25 20:17 UTC, joshkhdev approved these changes

2024-08-25 20:49 UTC, joshkhdev requested changes

2024-08-25 20:49 UTC, joshkhdev commented on docker-compose.yml
> +    restart: no
Нужно включить перезапуск контейнера, предлагаю с параметром unless-stopped

2024-08-25 20:49 UTC, joshkhdev commented on docker-compose.yml
> +    restart: no
Нужно включить перезапуск контейнера, предлагаю с параметром unless-stopped

2024-08-25 20:49 UTC, joshkhdev commented on docker-compose.yml
> +      - "ASPNETCORE_ENVIRONMENT=Development"
В докере запускаем release версию, значит ASPNETCORE_ENVIRONMENT=Production
Нужно поменять

2024-08-25 20:49 UTC, joshkhdev commented on src/PsyAssistPlatform.WebApi/appsettings.json
> +    "PsyAssistPlatformDb": "Host=psy-assist-platform-db;Port=5432;Include Error Detail=true;Database=psyAssistPlatform;Username=psyadmin;Password=12345"
Такой строке подключения тут не место, это явно привязывается к среде докера
Нужно либо убрать, либо перенести в appsettings.Production.json

2024-08-25 20:49 UTC, joshkhdev commented on src/PsyAssistPlatform.WebApi/appsettings.json
>  {
Настроек "Logging" не хватает, либо в этом файле, либо в appsettings.Production.json

2024-08-26 09:45 UTC, artcolumbo commented on docker-compose.yml
> +    restart: no
Done

2024-08-26 09:45 UTC, artcolumbo commented on docker-compose.yml
> +      - "ASPNETCORE_ENVIRONMENT=Development"
Done

2024-08-26 09:45 UTC, artcolumbo commented on docker-compose.yml
> +    restart: no
Done

2024-08-26 09:45 UTC, artcolumbo commented on src/PsyAssistPlatform.WebApi/appsettings.json
> +    "PsyAssistPlatformDb": "Host=psy-assist-platform-db;Port=5432;Include Error Detail=true;Database=psyAssistPlatform;Username=psyadmin;Password=12345"
Перенес

2024-08-26 09:47 UTC, artcolumbo commented on src/PsyAssistPlatform.WebApi/appsettings.json
>  {
"Logging" добавлено в appsettings.Production.json

2024-08-26 16:46 UTC, joshkhdev approved these changes

2024-08-26 18:31 UTC, miitrei approved these changes

2024-08-27 07:29 UTC, merged